### ISSUE TITLE
more clarity on what this project is

### ISSUE THREAD

**Issue by AndySchroder** [jb55/lnsocket#19]
I don't understand what this project is. How can a browser directly speak lightning? Is there a proxy server required to translate the websockets connection to a lightning node socket connection? Or, have you come up with a way to speak directly with the node over websockets? Also, can I use this for arbitrary message exchange, or are there specific messages that can be sent? Does this onion route messages over the lightning network, or can it only connect directly to the peer?

**Comment by jb55** [comment]
> Or, have you come up with a way to speak directly with the node over websockets

Yes. A browser can speak lightning directly because CLN can talk the websockets protocol. proxy server is only needed for secure connections (see https://github.com/jb55/ln-ws-proxy)

> Also, can I use this for arbitrary message exchange, or are there specific messages that can be sent

yes you can send custom messages as long as they use the lightning packet format.

> Does this onion route messages over the lightning network, or can it only connect directly to the peer

Only direct connections until we add support for that, but would be more complex and require gathering gossip and routes.
